config:
  send_anonymous_usage_stats: False
  use_colors: True
nba_monte_carlo:
  target: bv
  outputs:
    bv:
      type: bv_duckdb
      host: localhost
      port: 5433
      database: main
      schema: main
      delegate: dev
      api_port: 3456
    dev:
      type: duckdb
      threads: 8
      path: nba_monte_carlo.duckdb
